# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(692, 496)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 671, 431))
        self.frame.setStyleSheet("*{\n"
"background:rgb(238, 247, 242);\n"
"font-size:15px;\n"
"font-family:Century Gothic,sans-serif;\n"
"}\n"
"QFrame{\n"
"font-size:15px;\n"
"border-image : url(:/image/picture12.png);\n"
"border-style:dashed  \n"
"}\n"
"QPushButton{\n"
"background:#5CB3CC;\n"
"color:#fff;\n"
"border-radius:15px;\n"
"}\n"
"QLineEdit{\n"
"border-radius:15px;\n"
"color:#03a9f4;\n"
"}\n"
"lineEdit_ip{\n"
"background:#03a9f4;\n"
"color:#fff;\n"
"border-radius:15px;\n"
"}\n"
"textBrowser{\n"
"background:rgb(238, 247, 242);\n"
"color:#fff;\n"
"border-radius:15px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1.setGeometry(QtCore.QRect(50, 70, 161, 141))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 70, 161, 141))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 70, 161, 141))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 250, 161, 141))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 250, 161, 141))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(450, 250, 161, 141))
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_1.setText(_translate("MainWindow", "中央调度系统"))
        self.pushButton_2.setText(_translate("MainWindow", "中央监控系统"))
        self.pushButton_3.setText(_translate("MainWindow", "中央通信系统"))
        self.pushButton_4.setText(_translate("MainWindow", "串口助手"))
        self.pushButton_5.setText(_translate("MainWindow", "系统与设置"))
        self.pushButton_6.setText(_translate("MainWindow", "帮助"))
import qt_source_rc
